/*
 * Copyright 2009 Michael Chermside
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */
package com.mcherm.zithiacharsheet.client.model;

import com.mcherm.zithiacharsheet.client.model.SkillCatalog.SkillCategory;


/**
 * This consists of some specialized Java (an embedded DSL would be the proper
 * term) for defining certain data in the game such as the content for the
 * SkillCatalog and WeaponsCatalog.
 */
public class GameData {
    
    public static SkillCategory[] getSkillData() {
        return new SkillCategory[] {
            new SkillCategory("Arts Skills",
                new ZithiaSkill("acting", ZithiaStat.PRE, 4, 3, "Acting"),
                new ZithiaSkill("bard", ZithiaStat.INT, 6, 3, "Bard"),
                new ZithiaSkill("calligraphy", ZithiaStat.DEX, 3, 1, "Calligraphy"),
                new ZithiaSkill("dance", ZithiaStat.DEX, 3, 2, "Dance"),
                new ZithiaSkill("choreography", ZithiaStat.INT, 3, 2, "Dance Choreography"),
                new ZithiaSkill("drawing", ZithiaStat.DEX, 3, 2, "Drawing"),
                new ZithiaSkill("flowers", ZithiaStat.OBS, 3, 1, "Flower Arranging"),
                new ZithiaSkill("landscaping", ZithiaStat.OBS, 3, 2, "Landscaping"),
                new ZithiaSkill("musiccomposition", ZithiaStat.INT, 3, 3, "Music, Composition"),
                new ZithiaSkill("musicgeneral", ZithiaStat.PRE, 3, 2, "Music, General"),
                new ZithiaSkill("musicinstrument", ZithiaStat.DEX, 3, 2, "Music, Instrument"),
                new ZithiaSkill("oratory", ZithiaStat.PRE, 3, 2, "Oratory"),
                new ZithiaSkill("origami", ZithiaStat.PRE, 3, 2, "Origami"),
                new ZithiaSkill("painting", ZithiaStat.DEX, 3, 2, "Painting"),
                new ZithiaSkill("epicpoetry", ZithiaStat.INT, 3, 2, "Poetry, Epic"),
                new ZithiaSkill("lyricpoetry", ZithiaStat.INT, 3, 2, "Poetry, Lyric"),
                new ZithiaSkill("sculpting", ZithiaStat.DEX, 3, 3, "Sculpting"),
                new ZithiaSkill("singing", ZithiaStat.PRE, 3, 1, "Singing"),
                new ZithiaSkill("writingfiction", ZithiaStat.INT, 3, 2, "Writing, Fiction"),
                new ZithiaSkill("writinghistorical", ZithiaStat.INT, 3, 2, "Writing, Historical"),
                new ZithiaSkill("writingjokes", ZithiaStat.PRE, 2, 2, "Writing, Jokes"),
                new ZithiaSkill("writingpersuasive", ZithiaStat.PRE, 3, 2, "Writing, Persuasive")
            ),
            new SkillCategory("Athletic Skills",
                new ZithiaSkill("acrobatics", ZithiaStat.DEX, 5, 3, "Acrobatics"),
                new ZithiaSkill("breakfall", ZithiaStat.DEX, 3, 2, "Breakfall"),
                new ZithiaSkill("breathcontrol", ZithiaStat.CON, 6, 2, "Breath Control"),
                new ZithiaSkill("climbing", ZithiaStat.DEX, 0, 2, "Climbing"),
                new ZithiaSkill("diving", ZithiaStat.DEX, 1, 1, "Diving"),
                new ZithiaSkill("drinking", ZithiaStat.CON, 1, 1, "Drinking"),
                new ZithiaSkill("juggling", ZithiaStat.DEX, 3, 2, "Juggling"),
                new ZithiaSkill("jumping", ZithiaStat.STR, 0, 2, "Jumping"),
                new ZithiaSkill("running", ZithiaStat.CON, 2, 1, "Running, Distance"),
                new ZithiaSkill("sprinting", ZithiaStat.STR, 3, 1, "Running, Sprinting"),
                new ZithiaSkill("skiing", ZithiaStat.DEX, 4, 2, "Skiing"),
                new ZithiaSkill("sleeponthego", null, 5, 0, "Sleep on the Go"),
                new ZithiaSkill("sport", ZithiaStat.DEX, 1, 2, "Sport, Specific"),
                new ZithiaSkill("swimming", null, 4, 0, "Swimming")
            ),
            new SkillCategory("Combat Skills",
                new ZithiaSkill("ambidexterity", null, 6, 0, "Ambidexterity"),
                new ZithiaSkill("blindfighting", ZithiaStat.OBS, 4, 2, "Blind Fighting"),
                new ZithiaSkill("charioteering", ZithiaStat.DEX, 4, 2, "Charioteering"),
                new ZithiaSkill("disarm", ZithiaStat.STR, 3, 3, "Disarm"),
                new ZithiaSkill("horsebackcombat", ZithiaStat.DEX, 4, 2, "Horseback Combat"),
                new ZithiaSkill("horsebackarchery", ZithiaStat.DEX, 4, 2, "Horseback Archery"),
                new ZithiaSkill("pronefighting", ZithiaStat.DEX, 3, 1, "Prone Fighting"),
                new ZithiaSkill("quickdraw", ZithiaStat.DEX, 3, 1, "Quick Draw"),
                new ZithiaSkill("surpriseattack", ZithiaStat.DEX, 4, 3, "Suprise Attack"),
                new ZithiaSkill("targetshooting", null, 5, 0, "Target Shooting"),
                new ZithiaSkill("twoweaponcombat", null, 8, 0, "Two Weapon Combat"),
                new ZithiaSkill("underwatercombat", null, 3, 0, "Underwater Combat")
            ),
            new SkillCategory("Craftsman Skills",
                new ZithiaSkill("animaltrainer", ZithiaStat.PRE, 5, 3, "Animal Trainer"),
                new ZithiaSkill("specificanimaltrainer", ZithiaStat.PRE, 2, 2, "Animal Trainer, Specific"),
                new ZithiaSkill("armorer", ZithiaStat.STR, 5, 2, "Armorer"),
                new ZithiaSkill("blacksmith", ZithiaStat.STR, 3, 2, "Blacksmith"),
                new ZithiaSkill("boatmaker", ZithiaStat.INT, 3, 2, "Boatwright"),
                new ZithiaSkill("bower", ZithiaStat.DEX, 5, 2, "Bowyer/Fletcher"),
                new ZithiaSkill("brewer", ZithiaStat.INT, 3, 2, "Brewer"),
                new ZithiaSkill("carpentry", ZithiaStat.STR, 3, 2, "Carpentry"),
                new ZithiaSkill("cleaning", ZithiaStat.WILL, 1, 1, "Cleaning"),
                new ZithiaSkill("clockmaker", ZithiaStat.INT, 5, 3, "Clockmaker"),
                new ZithiaSkill("cobbler", ZithiaStat.DEX, 3, 1, "Cobbler"),
                new ZithiaSkill("cooking", ZithiaStat.INT, 2, 1, "Cooking"),
                new ZithiaSkill("falconry", ZithiaStat.PRE, 2, 2, "Falconry"),
                new ZithiaSkill("gemcutter", ZithiaStat.DEX, 3, 3, "Gem Cutter"),
                new ZithiaSkill("jeweler", ZithiaStat.DEX, 3, 2, "Jeweler"),
                new ZithiaSkill("leatherworker", ZithiaStat.INT, 2, 1, "Leather Worker"),
                new ZithiaSkill("locksmith", ZithiaStat.DEX, 3, 2, "Locksmith"),
                new ZithiaSkill("papermaker", ZithiaStat.INT, 3, 2, "Paper Maker"),
                new ZithiaSkill("potter", ZithiaStat.DEX, 3, 2, "Potter"),
                new ZithiaSkill("scribe", ZithiaStat.INT, 2, 2, "Scribe"),
                new ZithiaSkill("shipbuilding", ZithiaStat.INT, 4, 3, "Shipbuilding"),
                new ZithiaSkill("silkmaker", ZithiaStat.INT, 5, 2, "Silk Maker"),
                new ZithiaSkill("smelter", ZithiaStat.INT, 3, 2, "Smelter"),
                new ZithiaSkill("stonemason", ZithiaStat.STR, 3, 2, "Stonemason"),
                new ZithiaSkill("tailor", ZithiaStat.OBS, 3, 2, "Tailor"),
                new ZithiaSkill("weaponsmith", ZithiaStat.STR, 5, 2, "Weaponsmith"),
                new ZithiaSkill("weaver", ZithiaStat.INT, 4, 2, "Weaver"),
                new ZithiaSkill("woodworker", ZithiaStat.DEX, 3, 2, "Woodworker")
            ),
            new SkillCategory("General Skills",
                new ZithiaSkill("administration", ZithiaStat.PRE, 3, 2, "Administration"),
                new ZithiaSkill("agronomy", ZithiaStat.INT, 2, 1, "Agriculture, Agronomy"),
                new ZithiaSkill("livestock", ZithiaStat.INT, 2, 1, "Agriculture, Livestock"),
                new ZithiaSkill("lumberjack", ZithiaStat.STR, 2, 1, "Agriculture, Lumbering"),
                new ZithiaSkill("appraisal", ZithiaStat.INT, 3, 2, "Appraisal"),
                new ZithiaSkill("areaknowledge", ZithiaStat.INT, 1, 1, "Area Knowledge"),
                new ZithiaSkill("diplomacy", ZithiaStat.PRE, 4, 2, "Diplomacy"),
                new ZithiaSkill("directionsense", ZithiaStat.OBS, 3, 2, "Direction Sense"),
                new ZithiaSkill("etiquette", ZithiaStat.PRE, 3, 1, "Etiquette"),
                new ZithiaSkill("gampling", ZithiaStat.INT, 3, 2, "Gaming, Gambling"),
                new ZithiaSkill("specificgame", ZithiaStat.INT, 2, 1, "Gaming, Specific Game"),
                new ZithiaSkill("strategygame", ZithiaStat.INT, 3, 3, "Gaming, Strategic"),
                new ZithiaSkill("gesture", ZithiaStat.INT, 2, 2, "Gesture"),
                new ZithiaSkill("masseur", ZithiaStat.DEX, 2, 1, "Masseur"),
                new ZithiaSkill("meditation", ZithiaStat.WILL, 2, 2, "Meditation"),
                new ZithiaSkill("memorization", ZithiaStat.WILL, 6, 2, "Memorization"),
                new ZithiaSkill("merchant", ZithiaStat.INT, 3, 2, "Merchant"),
                new ZithiaSkill("haggling", ZithiaStat.PRE, 1, 1, "Merchant, Haggling"),
                new ZithiaSkill("flyingmount", ZithiaStat.DEX, 5, 3, "Riding, Specific, Flying"),
                new ZithiaSkill("riding", ZithiaStat.DEX, 2, 2, "Riding, Specific, Land"),
                new ZithiaSkill("rope", ZithiaStat.DEX, 2, 2, "Rope Use"),
                new ZithiaSkill("signlanguage", ZithiaStat.INT, 5, 3, "Sign Language"),
                new ZithiaSkill("signaling", ZithiaStat.INT, 3, 2, "Signaling"),
                new ZithiaSkill("teamster", ZithiaStat.PRE, 3, 2, "Teamster")
            ),
            new SkillCategory("Magical Skills",
                new ZithiaSkill("alchemy", ZithiaStat.INT, 6, 4, "Alchemy"),
                new ZithiaSkill("astrology", ZithiaStat.INT, 6, 4, "Astrology / Fortunes"),
                new ZithiaSkill("magicitemid", ZithiaStat.INT, 5, 3, "Magic Item Identification"),
                new ZithiaSkill("magicitemlore", ZithiaStat.INT, 4, 2, "Magic Item Lore"),
                new ZithiaSkill("runes", ZithiaStat.INT, 3, 2, "Magic Runes"),
                new ZithiaSkill("magictheory", ZithiaStat.INT, 3, 3, "Magic Theory, General"),
                new ZithiaSkill("magictheoryschool", ZithiaStat.INT, 4, 2, "Magic Theory, School"),
                new ZithiaSkill("planes", ZithiaStat.INT, 5, 3, "Planes"),
                new ZithiaSkill("spellid", ZithiaStat.OBS, 4, 3, "Spell Identification"),
                new ZithiaSkill("spellresearch", ZithiaStat.WILL, 3, 2, "Spell Research"),
                new ZithiaSkill("spellcasting", ZithiaStat.WILL, 5, 3, "Spellcasting"),
                new ZithiaSkill("schoolofmagic", ZithiaStat.WILL, 3, 2, "School of Magic"),
                new ZithiaSkill("personalstyle", ZithiaStat.WILL, 2, 1, "Personal Style Magic")
            ),
            new SkillCategory("Scholar Skills",
                new ZithiaSkill("accounting", ZithiaStat.INT, 3, 2, "Accounting"),
                new ZithiaSkill("anthropology", ZithiaStat.INT, 3, 2, "Anthropology"),
                new ZithiaSkill("archeology", ZithiaStat.INT, 3, 2, "Archeology"),
                new ZithiaSkill("architect", ZithiaStat.INT, 3, 2, "Architect"),
                new ZithiaSkill("astronomy", ZithiaStat.INT, 3, 2, "Astronomy"),
                new ZithiaSkill("botany", ZithiaStat.INT, 3, 2, "Biology, Botany"),
                new ZithiaSkill("zoology", ZithiaStat.INT, 3, 2, "Biology, Zoology"),
                new ZithiaSkill("chemistry", ZithiaStat.INT, 3, 2, "Chemistry"),
                new ZithiaSkill("chirography", ZithiaStat.DEX, 2, 2, "Chirography"),
                new ZithiaSkill("cryptography", ZithiaStat.INT, 4, 3, "Cryptography"),
                new ZithiaSkill("dentistry", ZithiaStat.DEX, 3, 2, "Dentistry"),
                new ZithiaSkill("drafting", ZithiaStat.DEX, 3, 2, "Drafting"),
                new ZithiaSkill("engineer", ZithiaStat.INT, 5, 2, "Engineer, Construction"),
                new ZithiaSkill("mining", ZithiaStat.INT, 3, 2, "Engineer, Mining"),
                new ZithiaSkill("sapping", ZithiaStat.INT, 3, 2, "Engineer, Sapping"),
                new ZithiaSkill("firstaid", ZithiaStat.INT, 2, 2, "First Aid"),
                new ZithiaSkill("forensics", ZithiaStat.INT, 3, 2, "Forensics"),
                new ZithiaSkill("geography", ZithiaStat.INT, 3, 2, "Geography"),
                new ZithiaSkill("geology", ZithiaStat.INT, 3, 2, "Geology"),
                new ZithiaSkill("heraldry", ZithiaStat.INT, 2, 1, "Heraldry"),
                new ZithiaSkill("herbalmedicine", ZithiaStat.INT, 5, 2, "Herbal Medicines"),
                new ZithiaSkill("history", ZithiaStat.INT, 3, 2, "History, General"),
                new ZithiaSkill("legends", ZithiaStat.INT, 3, 2, "History, Legends"),
                new ZithiaSkill("animalid", ZithiaStat.OBS, 3, 1, "Identification, Animal"),
                new ZithiaSkill("fungusid", ZithiaStat.OBS, 3, 1, "Identification, Fungus"),
                new ZithiaSkill("gemid", ZithiaStat.OBS, 2, 1, "Identification, Gem"),
                new ZithiaSkill("monsterid", ZithiaStat.OBS, 4, 2, "Identification, Monster"),
                new ZithiaSkill("plantid", ZithiaStat.OBS, 3, 1, "Identification, Plant"),
                new ZithiaSkill("weaponid", ZithiaStat.OBS, 2, 1, "Identification, Weapon"),
                new ZithiaSkill("specificknowledge", ZithiaStat.INT, 2, 1, "Knowledge, Specific"),
                new ZithiaSkill("law", ZithiaStat.INT, 4, 2, "Law"),
                new ZithiaSkill("literacy", null, 5, 0, "Literacy"),
                new ZithiaSkill("mathematics", ZithiaStat.INT, 3, 2, "Mathematics"),
                new ZithiaSkill("medicine", ZithiaStat.INT, 4, 3, "Medicine"),
                new ZithiaSkill("navigation", ZithiaStat.INT, 4, 2, "Navigation, Ocean"),
                new ZithiaSkill("philosophy", ZithiaStat.INT, 2, 2, "Philosophy"),
                new ZithiaSkill("physics", ZithiaStat.INT, 5, 2, "Physics"),
                new ZithiaSkill("politics", ZithiaStat.INT, 2, 1, "Political Science"),
                new ZithiaSkill("psychology", ZithiaStat.INT, 3, 2, "Psychology"),
                new ZithiaSkill("religion", ZithiaStat.INT, 3, 2, "Religion, General"),
                new ZithiaSkill("specificreligion", ZithiaStat.INT, 1, 1, "Religion, Specific"),
                new ZithiaSkill("research", ZithiaStat.INT, 2, 2, "Research"),
                new ZithiaSkill("sociology", ZithiaStat.INT, 3, 2, "Sociology"),
                new ZithiaSkill("strategy", ZithiaStat.INT, 3, 2, "Strategy"),
                new ZithiaSkill("cartography", ZithiaStat.INT, 3, 2, "Surveying-Cartography"),
                new ZithiaSkill("tactics", ZithiaStat.PRE, 4, 2, "Tactics"),
                new ZithiaSkill("teaching", ZithiaStat.INT, 3, 2, "Teaching"),
                new ZithiaSkill("veterinarian", ZithiaStat.INT, 3, 2, "Veterinarian")
            ),
            new SkillCategory("Thief/Spy Skills",
                new ZithiaSkill("bribery", ZithiaStat.PRE, 3, 2, "Bribery"),
                new ZithiaSkill("concealment", ZithiaStat.OBS, 1, 2, "Concealment"),
                new ZithiaSkill("detectlies", ZithiaStat.OBS, 4, 2, "Detect Lies"),
                new ZithiaSkill("disguise", ZithiaStat.PRE, 3, 2, "Disguise"),
                new ZithiaSkill("escape", ZithiaStat.DEX, 3, 3, "Escape"),
                new ZithiaSkill("evasion", ZithiaStat.INT, 3, 3, "Evasion"),
                new ZithiaSkill("fasttalk", ZithiaStat.PRE, 2, 2, "Fast Talk"),
                new ZithiaSkill("forgery", ZithiaStat.INT, 3, 3, "Forgery"),
                new ZithiaSkill("intelligenceanalysis", ZithiaStat.INT, 4, 3, "Intelligence Analysis"),
                new ZithiaSkill("interrogation", ZithiaStat.PRE, 3, 2, "Interrogation"),
                new ZithiaSkill("lipreading", ZithiaStat.OBS, 5, 2, "Lip Reading"),
                new ZithiaSkill("lockpicking", ZithiaStat.DEX, 4, 2, "Lockpicking"),
                new ZithiaSkill("pickpocket", ZithiaStat.DEX, 4, 1, "Pickpocket"),
                new ZithiaSkill("poisons", ZithiaStat.INT, 3, 2, "Poisons"),
                new ZithiaSkill("scrounging", ZithiaStat.INT, 2, 1, "Scrounging"),
                new ZithiaSkill("shadowing", ZithiaStat.OBS, 3, 2, "Shadowing"),
                new ZithiaSkill("slightofhand", ZithiaStat.DEX, 3, 3, "Slight of Hand"),
                new ZithiaSkill("soundanalysis", ZithiaStat.OBS, 4, 3, "Sound Analysis"),
                new ZithiaSkill("stealth", ZithiaStat.DEX, 0, 2, "Stealth"),
                new ZithiaSkill("streetwise", ZithiaStat.PRE, 3, 2, "Streetwise"),
                new ZithiaSkill("traps", ZithiaStat.INT, 5, 2, "Traps"),
                new ZithiaSkill("ventriloquism", ZithiaStat.PRE, 6, 1, "Ventriloquism"),
                new ZithiaSkill("voicemimicry", ZithiaStat.INT, 3, 2, "Voice Mimicry")
            ),
            new SkillCategory("Wilderness Skills",
                new ZithiaSkill("animallore", ZithiaStat.INT, 3, 2, "Animal Lore"),
                new ZithiaSkill("animalmimicry", ZithiaStat.OBS, 4, 2, "Animal Mimicry"),
                new ZithiaSkill("boating", ZithiaStat.INT, 2, 2, "Boating"),
                new ZithiaSkill("camouflage", ZithiaStat.OBS, 2, 2, "Camouflage"),
                new ZithiaSkill("firebuilding", ZithiaStat.WILL, 2, 1, "Fire Building"),
                new ZithiaSkill("fishing", ZithiaStat.INT, 1, 1, "Fishing"),
                new ZithiaSkill("foraging", ZithiaStat.OBS, 2, 1, "Foraging"),
                new ZithiaSkill("hunting", ZithiaStat.OBS, 3, 2, "Hunting"),
                new ZithiaSkill("meteorology", ZithiaStat.INT, 3, 2, "Meteorology"),
                new ZithiaSkill("mountaineering", ZithiaStat.STR, 3, 2, "Mountaineering"),
                new ZithiaSkill("orienteering", ZithiaStat.INT, 2, 2, "Orienteering"),
                new ZithiaSkill("plantlore", ZithiaStat.INT, 3, 2, "Plant Lore"),
                new ZithiaSkill("prospecting", ZithiaStat.INT, 3, 2, "Prospecting"),
                new ZithiaSkill("sailing", ZithiaStat.INT, 4, 2, "Sailing"),
                new ZithiaSkill("spelunking", ZithiaStat.INT, 3, 2, "Spelunking"),
                new ZithiaSkill("arcticsurvival", ZithiaStat.CON, 3, 2, "Survival, Arctic"),
                new ZithiaSkill("desertsurvival", ZithiaStat.CON, 3, 2, "Survival, Desert"),
                new ZithiaSkill("beachsurvival", ZithiaStat.CON, 3, 2, "Survival, Island/Beach"),
                new ZithiaSkill("junglesurvival", ZithiaStat.CON, 3, 2, "Survival, Jungle"),
                new ZithiaSkill("mountainsurvival", ZithiaStat.CON, 3, 2, "Survival, Mountains"),
                new ZithiaSkill("plainssurvival", ZithiaStat.CON, 3, 2, "Survival, Plains"),
                new ZithiaSkill("swampsurvival", ZithiaStat.CON, 3, 2, "Survival, Swampland"),
                new ZithiaSkill("woodssurvival", ZithiaStat.CON, 3, 2, "Survival, Woodlands"),
                new ZithiaSkill("tracking", ZithiaStat.OBS, 3, 2, "Tracking"),
                new ZithiaSkill("trapper", ZithiaStat.INT, 3, 2, "Trapper-Furrier")
            )
        };
    }

}
