package com.mcherm.zithiacharsheet.client;

import java.util.List;

import com.google.gwt.user.client.rpc.AsyncCallback;
import com.mcherm.zithiacharsheet.client.model.CharacterStorage;


/**
 * Pure boilerplace service which could in principle be autogenerated from the
 * interface SaveCharsheetService.
 * 
 * @see SaveCharsheetService
 */
public interface SaveCharsheetServiceAsync {
    void newCharsheet(AsyncCallback<CharacterStorage.CharacterMetadata> callback);
    void saveCharsheet(CharacterStorage data, AsyncCallback<Void> callback);
    void loadCharsheet(String characterId, AsyncCallback<String> callback);
    void listCharsheets(AsyncCallback<List<CharacterStorage.CharacterMetadata>> callback);
}

